#!/usr/bin/env python

Import('env')
Import('env_modules')

env_compat53 = env_modules.Clone()

if env["platform"] == "windows" or env["platform"] == "uwp":
    env_compat53.Append(CFLAGS=['/O0', '/std=c99'])
else:
    env_compat53.Append(CFLAGS=['-O0', '-std=c99'])


lua_sources = [
	"lstrlib.c",
	"lutf8lib.c",
	"ltablib.c"
	]

env_compat53.add_source_files(env.modules_sources, lua_sources)
