#!/usr/bin/env python

Import('env')
Import('env_modules')

env_compat53 = env_modules.Clone()
lua_include_path = "#modules/luascript/lib/luajit/src"

if env["platform"] == "windows" or env["platform"] == "uwp":
    env_compat53.Append(CFLAGS=[])
else:
    env_compat53.Append(CFLAGS=['-O0', '-std=c99'])

env_compat53.Append(CPPPATH=[lua_include_path])

lua_sources = [
	"lstrlib.c",
	"lutf8lib.c",
	"ltablib.c"
	]

env_compat53.add_source_files(env.modules_sources, lua_sources)
