#!/usr/bin/env python

Import('env')
Import('env_modules')

env_luajit = env_modules.Clone()

if env["platform"] == "windows" or env["platform"] == "uwp":
    env_luajit.Append(CFLAGS=['\O0', '\std=c99'])
else:
    env_luajit.Append(CFLAGS=['-O0', '-std=c99'])

lua_sources = [
	"lapi.c",
	"lauxlib.c",
	"lbaselib.c",
	"lcode.c",
	"ldblib.c",
	"ldebug.c",
	"ldo.c",
	"ldump.c",
	"lfunc.c",
	"lgc.c",
	"linit.c",
	"liolib.c",
	"llex.c",
	"lmathlib.c",
	"lmem.c",
	"loadlib.c",
	"lobject.c",
	"lopcodes.c",
	"loslib.c",
	"lparser.c",
	"lstate.c",
	"lstring.c",
	"lstrlib.c",
	"ltable.c",
	"ltablib.c",
	"ltm.c",
	"lundump.c",
	"lvm.c",
	"lzio.c",
	]

env_luajit.add_source_files(env.modules_sources, lua_sources)
